language: r
dist: trusty
cache: packages
sudo: required

r_packages:
 - testthat
 - covr

after_success:
 - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - r:oldrel 
      not_cran: true
      r_check_args: "--no-manual"
    - r: oldrel
      not_cran: false
      r_check_args: "--no-manual --as--cran"
    - r: release
      not_cran: true
      r_check_args: "--no-manual"
    - r: release
      not_cran: false
      r_check_args: "--no-manual --as--cran"
    - r: devel
      not_cran: true
      r_check_args: "--no-manual"
    - r: devel
      not_cran: false
      r_check_args: "--no-manual --as--cran"
